"""Basebreak Causal Two-World Engine and Verification Primitives.

P-10: Causal Two-World Engine implementation.
"""

from __future__ import annotations

from basebreak.causal.engine import (
    CausalBindingError,
    CausalEngineError,
    CausalExecutionEngine,
    EmptyCandidatePatchError,
    SandboxCollisionError,
    WorldExecutionOutput,
)
from basebreak.causal.harness import (
    BASEBREAK_JUDGE_CLAIM,
    BASEBREAK_THESIS,
    format_judge_proof_summary,
    render_judge_proof_markdown,
    run_causal_verification_slice,
)
from basebreak.causal.materializer import (
    CausalRepositoryMaterializer,
    GitRepositoryMaterializer,
)
from basebreak.causal.receipt import (
    CAUSAL_RECEIPT_SCHEMA_VERSION,
    CausalReceiptError,
    CausalReceiptIntegrityError,
    CausalReceiptTamperingError,
    LocalCausalReceipt,
    WorldExecutionFact,
    build_canonical_receipt_payload,
    compute_receipt_digest,
    create_causal_receipt,
    verify_causal_receipt_integrity,
)
from basebreak.causal.reconciliation import (
    CausalTransition,
    ReconciliationFact,
    reconcile_causal_transition,
)
from basebreak.causal.subtraction import (
    AmbiguousSubtractionError,
    CallerAuthorityError,
    CandidateDeltaSubtractor,
    CandidateIdentityMismatchError,
    CandidateSubtractionError,
    CounterfactualDeltaPlan,
    DigestTamperingError,
    EmptySubtractionError,
    InvalidSubtractionError,
    ParsedCandidatePatch,
    ParsedDiffHunk,
    ParsedFileDiff,
    ProtectedSurfaceSubtractionError,
    SecretPolicySubtractionError,
    SubtractionRequest,
    SubtractionStrategyType,
    UnsupportedStrategyError,
    invert_patch,
    parse_candidate_patch,
    plan_candidate_delta_subtraction,
    plan_subtraction_from_snapshot,
)

__all__ = [
    "AmbiguousSubtractionError",
    "BASEBREAK_JUDGE_CLAIM",
    "BASEBREAK_THESIS",
    "CAUSAL_RECEIPT_SCHEMA_VERSION",
    "CallerAuthorityError",
    "CandidateDeltaSubtractor",
    "CandidateIdentityMismatchError",
    "CandidateSubtractionError",
    "CausalBindingError",
    "CausalEngineError",
    "CausalExecutionEngine",
    "CausalReceiptError",
    "CausalReceiptIntegrityError",
    "CausalReceiptTamperingError",
    "CausalRepositoryMaterializer",
    "CausalTransition",
    "CounterfactualDeltaPlan",
    "DigestTamperingError",
    "EmptyCandidatePatchError",
    "EmptySubtractionError",
    "GitRepositoryMaterializer",
    "InvalidSubtractionError",
    "LocalCausalReceipt",
    "ParsedCandidatePatch",
    "ParsedDiffHunk",
    "ParsedFileDiff",
    "ProtectedSurfaceSubtractionError",
    "ReconciliationFact",
    "SandboxCollisionError",
    "SecretPolicySubtractionError",
    "SubtractionRequest",
    "SubtractionStrategyType",
    "UnsupportedStrategyError",
    "WorldExecutionFact",
    "WorldExecutionOutput",
    "build_canonical_receipt_payload",
    "compute_receipt_digest",
    "create_causal_receipt",
    "format_judge_proof_summary",
    "invert_patch",
    "parse_candidate_patch",
    "plan_candidate_delta_subtraction",
    "plan_subtraction_from_snapshot",
    "reconcile_causal_transition",
    "render_judge_proof_markdown",
    "run_causal_verification_slice",
    "verify_causal_receipt_integrity",
]
