"""Nebius Token Factory adapter package.

Exposes bounded model client, model constants, and adapter error classes.
"""

from .client import (
    ChatMessage,
    MissingCredentialError,
    ModelAdapterError,
    ModelClientConfig,
    ModelClientResult,
    ModelConfigError,
    ModelIdentityMismatchError,
    ModelNetworkError,
    ModelProviderError,
    ModelResponseFormatError,
    ModelTimeoutError,
    NebiusModelClient,
    TokenUsage,
    TransportCallable,
    TransportResponse,
    default_urllib_transport,
)
from .models import (
    CANDIDATE_DEEP_MODEL,
    CHAT_COMPLETIONS_PATH,
    DEFAULT_API_BASE_URL,
    DEFAULT_MAX_TOKENS,
    DEFAULT_PRIMARY_MODEL,
    DEFAULT_TEMPERATURE,
    DEFAULT_TIMEOUT_SECONDS,
    MAX_MAX_TOKENS,
    MAX_PROMPT_CHARACTERS,
    MAX_RESPONSE_CHARACTERS,
    MAX_TEMPERATURE,
    MAX_TIMEOUT_SECONDS,
    MIN_MAX_TOKENS,
    MIN_TEMPERATURE,
    MIN_TIMEOUT_SECONDS,
)

__all__ = [
    "CANDIDATE_DEEP_MODEL",
    "CHAT_COMPLETIONS_PATH",
    "ChatMessage",
    "DEFAULT_API_BASE_URL",
    "DEFAULT_MAX_TOKENS",
    "DEFAULT_PRIMARY_MODEL",
    "DEFAULT_TEMPERATURE",
    "DEFAULT_TIMEOUT_SECONDS",
    "MAX_MAX_TOKENS",
    "MAX_PROMPT_CHARACTERS",
    "MAX_RESPONSE_CHARACTERS",
    "MAX_TEMPERATURE",
    "MAX_TIMEOUT_SECONDS",
    "MIN_MAX_TOKENS",
    "MIN_TEMPERATURE",
    "MIN_TIMEOUT_SECONDS",
    "MissingCredentialError",
    "ModelAdapterError",
    "ModelClientConfig",
    "ModelClientResult",
    "ModelConfigError",
    "ModelIdentityMismatchError",
    "ModelNetworkError",
    "ModelProviderError",
    "ModelResponseFormatError",
    "ModelTimeoutError",
    "NebiusModelClient",
    "TokenUsage",
    "TransportCallable",
    "TransportResponse",
    "default_urllib_transport",
]
