"""Verifier isolation, sealed witness boundary, and execution contracts.

P-08: Verifier Isolation & Sealed Challenge Boundary.
"""

from basebreak.verifier.context import (
    VERIFIER_CONTEXT_SCHEMA_VERSION,
    BuilderAuthoritySmugglingError,
    MutableWorkspacePathError,
    UnpinnedSourceError,
    UntrustedBuilderInputError,
    VerifierContextEnvelope,
    VerifierContextError,
    VerifierDigestMismatchError,
    VerifierExecutionPolicy,
    VerifierInputClassification,
)
from basebreak.verifier.sandbox import (
    DEFAULT_VERIFIER_SANDBOX_IMAGE,
    DEFAULT_VERIFIER_TIMEOUT_SECONDS,
    DEFAULT_VERIFIER_WORKSPACE_PATH,
    BuilderSandboxReuseError,
    BuilderWorkspaceInheritanceError,
    HostExecutionFallbackError,
    MissingSandboxIdentityError,
    SimulationFallbackError,
    VerifierMaterializationError,
    VerifierSandboxConfig,
    VerifierSandboxError,
    VerifierSandboxManager,
    VerifierSandboxSession,
    VerifierTreeDigestMismatchError,
)
from basebreak.verifier.witness_store import (
    SealedWitnessRecord,
    TrustedWitnessVault,
    UntrustedWitnessAuthorityError,
    WitnessArtifact,
    WitnessIntegrityError,
    WitnessPathSecurityError,
    WitnessProtectedSurfaceCollisionError,
    WitnessSecretError,
    WitnessTamperingError,
)

__all__ = [
    "DEFAULT_VERIFIER_SANDBOX_IMAGE",
    "DEFAULT_VERIFIER_TIMEOUT_SECONDS",
    "DEFAULT_VERIFIER_WORKSPACE_PATH",
    "VERIFIER_CONTEXT_SCHEMA_VERSION",
    "BuilderAuthoritySmugglingError",
    "BuilderSandboxReuseError",
    "BuilderWorkspaceInheritanceError",
    "HostExecutionFallbackError",
    "MissingSandboxIdentityError",
    "MutableWorkspacePathError",
    "SealedWitnessRecord",
    "SimulationFallbackError",
    "TrustedWitnessVault",
    "UnpinnedSourceError",
    "UntrustedBuilderInputError",
    "UntrustedWitnessAuthorityError",
    "VerifierContextEnvelope",
    "VerifierContextError",
    "VerifierDigestMismatchError",
    "VerifierExecutionPolicy",
    "VerifierInputClassification",
    "VerifierMaterializationError",
    "VerifierSandboxConfig",
    "VerifierSandboxError",
    "VerifierSandboxManager",
    "VerifierSandboxSession",
    "VerifierTreeDigestMismatchError",
    "WitnessArtifact",
    "WitnessIntegrityError",
    "WitnessPathSecurityError",
    "WitnessProtectedSurfaceCollisionError",
    "WitnessSecretError",
    "WitnessTamperingError",
]
