"""Basebreak Contract Compiler package.

Converts untrusted natural-language engineering tasks into machine-verifiable,
reviewable verification contracts.
"""

from __future__ import annotations

from basebreak.compiler.ingestion import (
    DEFAULT_MAX_TASK_BYTES,
    MIN_TASK_NON_WHITESPACE_CHARS,
    EmptyTaskInputError,
    InvalidTaskContentError,
    NormalizedTask,
    TaskIngestionError,
    TaskSizeLimitExceededError,
    ingest_task,
    normalize_task_text,
)
from basebreak.compiler.requirements import (
    DEFAULT_PROPOSAL_MAX_TOKENS,
    DEFAULT_REQUIREMENTS_MODEL,
    InvalidModelConfigurationError,
    MalformedModelOutputError,
    NemotronRequirementProposer,
    ProposedRequirement,
    RequirementProposalError,
    RequirementProposalResult,
    UnsupportedCitationError,
    parse_and_validate_requirements,
)
from basebreak.compiler.semantics import (
    DEFAULT_SEMANTICS_MAX_TOKENS,
    DEFAULT_SEMANTICS_MODEL,
    CertaintyLevel,
    ChangeSemanticsClassification,
    ChangeSemanticsError,
    DeterministicClassificationFact,
    MalformedModelSemanticsError,
    ModelChangeProposal,
    NemotronSemanticsClassifier,
    classify_semantics_deterministically,
    parse_and_validate_semantics_proposal,
    reconcile_semantics,
)
from basebreak.compiler.validator import (
    MAX_CITATION_LENGTH,
    MAX_REQUIREMENTS_COUNT,
    MAX_STATEMENT_LENGTH,
    MIN_REQUIREMENTS_COUNT,
    MIN_STATEMENT_LENGTH,
    ContractValidationError,
    ContradictoryRequirementsError,
    DuplicateRequirementIdError,
    ForbiddenActionViolationError,
    InvalidChangeClassError,
    InvalidRequirementIdError,
    MissingRequirementIdError,
    RequirementCountLimitExceededError,
    RequirementSizeLimitExceededError,
    UnsupportedScopeError,
    ValidatedContract,
    ValidatedRequirement,
    assign_deterministic_requirement_ids,
    derive_requirement_id,
    validate_contract,
)

__all__ = [
    "DEFAULT_MAX_TASK_BYTES",
    "DEFAULT_PROPOSAL_MAX_TOKENS",
    "DEFAULT_REQUIREMENTS_MODEL",
    "DEFAULT_SEMANTICS_MAX_TOKENS",
    "DEFAULT_SEMANTICS_MODEL",
    "MAX_CITATION_LENGTH",
    "MAX_REQUIREMENTS_COUNT",
    "MAX_STATEMENT_LENGTH",
    "MIN_REQUIREMENTS_COUNT",
    "MIN_STATEMENT_LENGTH",
    "MIN_TASK_NON_WHITESPACE_CHARS",
    "CertaintyLevel",
    "ChangeSemanticsClassification",
    "ChangeSemanticsError",
    "ContractValidationError",
    "ContradictoryRequirementsError",
    "DeterministicClassificationFact",
    "DuplicateRequirementIdError",
    "EmptyTaskInputError",
    "ForbiddenActionViolationError",
    "InvalidChangeClassError",
    "InvalidModelConfigurationError",
    "InvalidRequirementIdError",
    "InvalidTaskContentError",
    "MalformedModelOutputError",
    "MalformedModelSemanticsError",
    "MissingRequirementIdError",
    "ModelChangeProposal",
    "NemotronRequirementProposer",
    "NemotronSemanticsClassifier",
    "NormalizedTask",
    "ProposedRequirement",
    "RequirementCountLimitExceededError",
    "RequirementProposalError",
    "RequirementProposalResult",
    "RequirementSizeLimitExceededError",
    "TaskIngestionError",
    "TaskSizeLimitExceededError",
    "UnsupportedCitationError",
    "UnsupportedScopeError",
    "ValidatedContract",
    "ValidatedRequirement",
    "assign_deterministic_requirement_ids",
    "classify_semantics_deterministically",
    "derive_requirement_id",
    "ingest_task",
    "normalize_task_text",
    "parse_and_validate_requirements",
    "parse_and_validate_semantics_proposal",
    "reconcile_semantics",
    "validate_contract",
]
