"""Basebreak Contract Compiler package.

Converts untrusted natural-language engineering tasks into machine-verifiable,
reviewable verification contracts.
"""

from __future__ import annotations

from basebreak.compiler.ingestion import (
    DEFAULT_MAX_TASK_BYTES,
    MIN_TASK_NON_WHITESPACE_CHARS,
    EmptyTaskInputError,
    InvalidTaskContentError,
    NormalizedTask,
    TaskIngestionError,
    TaskSizeLimitExceededError,
    ingest_task,
    normalize_task_text,
)
from basebreak.compiler.requirements import (
    DEFAULT_PROPOSAL_MAX_TOKENS,
    DEFAULT_REQUIREMENTS_MODEL,
    InvalidModelConfigurationError,
    MalformedModelOutputError,
    NemotronRequirementProposer,
    ProposedRequirement,
    RequirementProposalError,
    RequirementProposalResult,
    UnsupportedCitationError,
    parse_and_validate_requirements,
)
from basebreak.compiler.review import (
    ReviewApprovalError,
    ReviewBundle,
    ReviewDecision,
    ReviewError,
    ReviewExitCode,
    ReviewOperationError,
    ReviewResult,
    ReviewSchemaError,
    ReviewSession,
    ReviewStatus,
    create_review_bundle,
    create_review_bundle_from_contract,
)
from basebreak.compiler.semantics import (
    SEMANTICS_SYSTEM_PROMPT,
    CertaintyLevel,
    ChangeSemanticsClassification,
    ChangeSemanticsError,
    DeterministicClassificationFact,
    MalformedModelSemanticsError,
    ModelChangeProposal,
    classify_semantics_deterministically,
    parse_and_validate_semantics_proposal,
    reconcile_semantics,
)
from basebreak.compiler.validator import (
    MAX_CITATION_LENGTH,
    MAX_RATIONALE_LENGTH,
    MAX_REQUIREMENT_ID_LENGTH,
    MAX_REQUIREMENTS_COUNT,
    MAX_STATEMENT_LENGTH,
    MIN_REQUIREMENTS_COUNT,
    ContractValidationError,
    ContradictoryRequirementsError,
    DuplicateRequirementIdError,
    ForbiddenActionViolationError,
    InvalidCitationError,
    InvalidRequirementIdError,
    MissingRequirementIdError,
    RequirementCountLimitExceededError,
    RequirementIdCollisionError,
    RequirementSizeLimitExceededError,
    UnresolvedChangeClassError,
    UnsupportedScopeError,
    ValidatedContract,
    ValidatedRequirement,
    derive_requirement_id,
    validate_contract,
)

__all__ = [
    "DEFAULT_MAX_TASK_BYTES",
    "DEFAULT_PROPOSAL_MAX_TOKENS",
    "DEFAULT_REQUIREMENTS_MODEL",
    "MAX_CITATION_LENGTH",
    "MAX_RATIONALE_LENGTH",
    "MAX_REQUIREMENT_ID_LENGTH",
    "MAX_REQUIREMENTS_COUNT",
    "MAX_STATEMENT_LENGTH",
    "MIN_REQUIREMENTS_COUNT",
    "MIN_TASK_NON_WHITESPACE_CHARS",
    "CertaintyLevel",
    "ChangeSemanticsClassification",
    "ChangeSemanticsError",
    "ContradictoryRequirementsError",
    "ContractValidationError",
    "DeterministicClassificationFact",
    "DuplicateRequirementIdError",
    "EmptyTaskInputError",
    "ForbiddenActionViolationError",
    "InvalidCitationError",
    "InvalidModelConfigurationError",
    "InvalidRequirementIdError",
    "InvalidTaskContentError",
    "MalformedModelOutputError",
    "MalformedModelSemanticsError",
    "MissingRequirementIdError",
    "ModelChangeProposal",
    "NemotronRequirementProposer",
    "NormalizedTask",
    "ProposedRequirement",
    "RequirementCountLimitExceededError",
    "RequirementIdCollisionError",
    "RequirementProposalError",
    "RequirementProposalResult",
    "RequirementSizeLimitExceededError",
    "ReviewApprovalError",
    "ReviewBundle",
    "ReviewDecision",
    "ReviewError",
    "ReviewExitCode",
    "ReviewOperationError",
    "ReviewResult",
    "ReviewSchemaError",
    "ReviewSession",
    "ReviewStatus",
    "SEMANTICS_SYSTEM_PROMPT",
    "TaskIngestionError",
    "TaskSizeLimitExceededError",
    "UnresolvedChangeClassError",
    "UnsupportedCitationError",
    "UnsupportedScopeError",
    "ValidatedContract",
    "ValidatedRequirement",
    "classify_semantics_deterministically",
    "create_review_bundle",
    "create_review_bundle_from_contract",
    "derive_requirement_id",
    "ingest_task",
    "normalize_task_text",
    "parse_and_validate_requirements",
    "parse_and_validate_semantics_proposal",
    "reconcile_semantics",
    "validate_contract",
]
