"""Basebreak Contract Compiler package.

Converts untrusted natural-language engineering tasks into machine-verifiable,
reviewable verification contracts.
"""

from __future__ import annotations

from basebreak.compiler.ingestion import (
    DEFAULT_MAX_TASK_BYTES,
    MIN_TASK_NON_WHITESPACE_CHARS,
    EmptyTaskInputError,
    InvalidTaskContentError,
    NormalizedTask,
    TaskIngestionError,
    TaskSizeLimitExceededError,
    ingest_task,
    normalize_task_text,
)
from basebreak.compiler.requirements import (
    DEFAULT_PROPOSAL_MAX_TOKENS,
    DEFAULT_REQUIREMENTS_MODEL,
    InvalidModelConfigurationError,
    MalformedModelOutputError,
    NemotronRequirementProposer,
    ProposedRequirement,
    RequirementProposalError,
    RequirementProposalResult,
    UnsupportedCitationError,
    parse_and_validate_requirements,
)
from basebreak.compiler.semantics import (
    DEFAULT_SEMANTICS_MAX_TOKENS,
    DEFAULT_SEMANTICS_MODEL,
    AmbiguousSemanticsError,
    CertaintyLevel,
    ChangeSemanticsClassification,
    InvalidChangeClassError,
    MalformedClassificationOutputError,
    NemotronSemanticsClassifier,
    SemanticsClassificationError,
    classify_semantics_deterministically,
    parse_and_validate_classification,
)
from basebreak.compiler.validator import (
    MAX_REQUIREMENTS_COUNT,
    MAX_STATEMENT_LENGTH,
    MIN_REQUIREMENTS_COUNT,
    MIN_STATEMENT_LENGTH,
    ContractScopeExceededError,
    ContractValidationError,
    ContradictoryRequirementsError,
    DuplicateRequirementIdError,
    ForbiddenActionViolationError,
    InvalidRequirementIdError,
    ValidatedContract,
    ValidatedRequirement,
    assign_deterministic_requirement_ids,
    validate_contract,
)

__all__ = [
    "AmbiguousSemanticsError",
    "CertaintyLevel",
    "ChangeSemanticsClassification",
    "ContractScopeExceededError",
    "ContractValidationError",
    "ContradictoryRequirementsError",
    "DEFAULT_MAX_TASK_BYTES",
    "DEFAULT_PROPOSAL_MAX_TOKENS",
    "DEFAULT_REQUIREMENTS_MODEL",
    "DEFAULT_SEMANTICS_MAX_TOKENS",
    "DEFAULT_SEMANTICS_MODEL",
    "DuplicateRequirementIdError",
    "EmptyTaskInputError",
    "ForbiddenActionViolationError",
    "InvalidChangeClassError",
    "InvalidModelConfigurationError",
    "InvalidRequirementIdError",
    "InvalidTaskContentError",
    "MAX_REQUIREMENTS_COUNT",
    "MAX_STATEMENT_LENGTH",
    "MIN_REQUIREMENTS_COUNT",
    "MIN_STATEMENT_LENGTH",
    "MIN_TASK_NON_WHITESPACE_CHARS",
    "MalformedClassificationOutputError",
    "MalformedModelOutputError",
    "NemotronRequirementProposer",
    "NemotronSemanticsClassifier",
    "NormalizedTask",
    "ProposedRequirement",
    "RequirementProposalError",
    "RequirementProposalResult",
    "SemanticsClassificationError",
    "TaskIngestionError",
    "TaskSizeLimitExceededError",
    "UnsupportedCitationError",
    "ValidatedContract",
    "ValidatedRequirement",
    "assign_deterministic_requirement_ids",
    "classify_semantics_deterministically",
    "ingest_task",
    "normalize_task_text",
    "parse_and_validate_classification",
    "parse_and_validate_requirements",
    "validate_contract",
]
