"""Basebreak evidence and deterministic fact authority primitives."""

from basebreak.evidence.append_model import (
    EvidenceConflictError,
    EvidenceError,
    EvidenceIdentity,
    EvidenceRebindingError,
    EvidenceRecord,
    EvidenceSequenceError,
    EvidenceStore,
    RunIdentity,
    authoritative_candidate_equals,
    authoritative_candidate_payload,
)
from basebreak.evidence.artifact import (
    Artifact,
    ArtifactDigest,
    ArtifactReference,
    DigestAlgorithm,
    artifact_from_bytes,
    artifact_from_domain_object,
    artifact_from_text,
    compute_bytes_digest,
    compute_domain_digest,
    compute_text_digest,
)
from basebreak.evidence.capture import (
    DEFAULT_MAX_CAPTURE_BYTES,
    CapturedOutput,
    CapturedStream,
    StreamType,
    capture_output,
    capture_stream,
    sanitize_text,
)
from basebreak.evidence.provenance import (
    ProvenanceLaunderingError,
    ProvenanceTransitionError,
    assert_provenance_not_verdict,
    has_execution_result,
    is_live_execution,
    is_recorded_live,
    is_successful_execution,
    validate_provenance_derivation,
    validate_provenance_transition,
)
from basebreak.evidence.snapshot import VerdictInputSnapshot

__all__ = [
    "DEFAULT_MAX_CAPTURE_BYTES",
    "Artifact",
    "ArtifactDigest",
    "ArtifactReference",
    "CapturedOutput",
    "CapturedStream",
    "DigestAlgorithm",
    "EvidenceConflictError",
    "EvidenceError",
    "EvidenceIdentity",
    "EvidenceRebindingError",
    "EvidenceRecord",
    "EvidenceSequenceError",
    "EvidenceStore",
    "ProvenanceLaunderingError",
    "ProvenanceTransitionError",
    "RunIdentity",
    "StreamType",
    "VerdictInputSnapshot",
    "artifact_from_bytes",
    "artifact_from_domain_object",
    "artifact_from_text",
    "assert_provenance_not_verdict",
    "authoritative_candidate_equals",
    "authoritative_candidate_payload",
    "capture_output",
    "capture_stream",
    "compute_bytes_digest",
    "compute_domain_digest",
    "compute_text_digest",
    "has_execution_result",
    "is_live_execution",
    "is_recorded_live",
    "is_successful_execution",
    "sanitize_text",
    "validate_provenance_derivation",
    "validate_provenance_transition",
]
